# Generated by Django 4.0.3 on 2022-03-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOf', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('distance', models.CharField(max_length=100)),
                ('packageType', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
