# Generated by Django 4.0.3 on 2022-03-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='typeOf',
            field=models.CharField(choices=[('Document', 'DOCUMENT'), ('parcel', 'PARCEL')], default='document', max_length=100),
        ),
    ]
