# Generated by Django 4.0.3 on 2022-03-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_pricing_typeof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='packageType',
        ),
    ]
