# Generated by Django 4.0.3 on 2022-03-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_remove_pricing_distance_remove_pricing_packagetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='size',
            field=models.CharField(choices=[('less than 1 m', '<1 m'), ('1-4 m', '1-4 M'), ('4-9 m', '4-9 M'), ('10-15 m', '10-15 M')], default='less than 1 m', max_length=100),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='weight',
            field=models.CharField(choices=[('Less than 1 kg', '>1KG'), ('1-4kg', '1-4 KG'), ('5-9 kg', '5-9 KG'), ('10-19 kg', '10-19 KG'), ('20-49 kg', '20-49 KG'), ('50-99 kg', '50-99 KG'), ('100+ kg', '100+ KG')], default='less than 1 kg', max_length=100),
        ),
    ]
