# Generated by Django 4.0.3 on 2022-04-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_alter_pricing_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='size',
            field=models.CharField(choices=[('Less than 1 m', '<1 m'), ('1-4 m', '1-4 M'), ('4-9 m', '4-9 M'), ('10-15 m', '10-15 M')], default='less than 1 m', max_length=100),
        ),
    ]
