# Generated by Django 4.0.3 on 2022-03-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0006_remove_ship_username_ship_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='email',
            field=models.EmailField(default='123@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
