# Generated by Django 4.0.3 on 2022-03-28 04:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0007_ship_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='tracking_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
