# Generated by Django 4.0.3 on 2022-03-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0008_ship_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='package_type',
            field=models.CharField(default='cheap', max_length=100),
            preserve_default=False,
        ),
    ]
