# Generated by Django 4.0.3 on 2022-03-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0009_ship_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='payment_type',
            field=models.CharField(default='cash on delivery', max_length=100),
            preserve_default=False,
        ),
    ]
