# Generated by Django 4.0.3 on 2022-04-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0010_ship_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='delivery_date',
            field=models.CharField(default='April 1,2022', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ship',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ship',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ship',
            name='size',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ship',
            name='weight',
            field=models.CharField(max_length=100),
        ),
    ]
