# Generated by Django 4.0.3 on 2022-04-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0012_ship_assignment_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ship',
            old_name='assignment_driver',
            new_name='assigned_driver',
        ),
    ]
