# Generated by Django 4.0.3 on 2022-04-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0013_rename_assignment_driver_ship_assigned_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
