# Generated by Django 4.0.3 on 2022-04-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0014_ship_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='name',
        ),
    ]
