# Generated by Django 4.0.3 on 2022-04-13 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_driveruser_vehicle_number_user_vehicle_number'),
        ('shipment', '0015_remove_ship_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.UUIDField()),
                ('driver_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.driveruser')),
            ],
        ),
    ]
