# Generated by Django 4.0.3 on 2022-03-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
