# Generated by Django 4.0.3 on 2022-03-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_driveruser_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='license',
            field=models.CharField(default=12332, max_length=100),
            preserve_default=False,
        ),
    ]
