# Generated by Django 4.0.3 on 2022-03-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveruser',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
