# Generated by Django 4.0.3 on 2022-03-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='password',
            field=models.CharField(default=123123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeruser',
            name='username',
            field=models.CharField(default=12321, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driveruser',
            name='password',
            field=models.CharField(default='123123', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driveruser',
            name='username',
            field=models.CharField(default='sdqsdas', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
