# Generated by Django 4.0.3 on 2022-03-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_customeruser_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveruser',
            name='vehicle_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
